-- Limpar base antiga para evitar mistura
TRUNCATE TABLE conhecimento_site;

INSERT INTO conhecimento_site (sistema, categoria, titulo, conteudo, tags, ordem, ativo) VALUES
('STS', 'Tutorial', 'Guia Rápido STS #106 - Documentos Fiscais - Pagamento - Rateio', 'Aprenda como realizar o rateio de pagamentos de documentos fiscais no sistema STS (Terceiro Setor). Link do vídeo: https://www.youtube.com/watch?v=frJWk7Agfpw', 'sts, saude, fiscal, pagamento, rateio', 1, 1),
('STS', 'Tutorial', 'Guia Rápido STS #105 - Documentos Fiscais - Recebimento', 'Passo a passo para o recebimento de documentos fiscais no sistema de Terceiro Setor. Link do vídeo: https://www.youtube.com/watch?v=rZDw2OsBAbs', 'sts, saude, fiscal, recebimento', 2, 1),
('STS', 'Tutorial', 'Guia Rápido STS #104 - Documentos Fiscais - Pagamento - Importar XML', 'Como importar XML para pagamento de documentos fiscais no sistema STS. Link do vídeo: https://www.youtube.com/watch?v=wGOwVN6-kvg', 'sts, saude, xml, importacao, fiscal', 3, 1),
('STS', 'Tutorial', 'Guia Rápido STS #103 - Análise de Solicitação de Aplicação Financeira', 'Procedimento para analisar solicitações de aplicação financeira no Terceiro Setor. Link do vídeo: https://www.youtube.com/watch?v=vlv5rFijgbo', 'sts, saude, aplicacao, financeira', 4, 1),
('STS', 'Tutorial', 'Guia Rápido STS #101 - Registros Bancários - Tarifas Bancárias - Devolução', 'Gestão de devolução de tarifas bancárias no sistema STS. Link do vídeo: https://www.youtube.com/watch?v=tqQmUq2jnXc', 'sts, saude, banco, tarifa, devolucao', 5, 1),
('STS', 'Tutorial', 'Guia Rápido STS #098 - Registros Bancários - Aplicação Financeira - Rendimentos', 'Lançamento de rendimentos de aplicações financeiras no Terceiro Setor. Link do vídeo: https://www.youtube.com/watch?v=XC4dmEJfWSM', 'sts, saude, rendimentos, banco', 6, 1),
('STS', 'Tutorial', 'Guia Rápido STS #094 - Registros Bancários - Configurações', 'Configurações de registros bancários para o sistema STS. Link do vídeo: https://www.youtube.com/watch?v=TbMP7_gvf80', 'sts, saude, configuracao, banco', 7, 1),
('SCPI', 'Transparência', 'Guia Rápido STS #093 - Portal Transparência do Terceiro Setor', 'Configuração e uso do Portal da Transparência para entidades do Terceiro Setor. Link do vídeo: https://www.youtube.com/watch?v=JAuiTIIiZgg', 'scpi, transparencia, sts, portal', 8, 1),
('SCPI', 'Gestão', 'Guia Rápido STS #082 - Dashboard do Terceiro Setor Administrador', 'Visão geral do Dashboard para administradores no sistema SCPI/STS. Link do vídeo: https://www.youtube.com/watch?v=_FiYgdk-kng', 'scpi, dashboard, gestao, sts', 9, 1),
('SCPI', 'Relatório', 'Guia Rápido STS #081 - Relatório Conclusivo', 'Como gerar o relatório conclusivo no sistema SCPI. Link do vídeo: https://www.youtube.com/watch?v=r31XTf_sL8c', 'scpi, relatorio, conclusivo', 10, 1),
('SIP', 'eSocial', 'Guia Rápido SIP #023 - eSocial - S-2220 - Monitoramento da Saúde do Trabalhador', 'Procedimento para envio do evento S-2220 (Saúde do Trabalhador) ao eSocial pelo sistema SIP. Link do vídeo: https://www.youtube.com/watch?v=RY1OZh7DNoc', 'sip, esocial, saude, s2220', 11, 1),
('SIP', 'eSocial', 'Guia Rápido SIP #024 - eSocial - Menus 4.34', 'Novidades e atualizações nos menus do eSocial na versão 4.34 do SIP. Link do vídeo: https://www.youtube.com/watch?v=Zs-5osP4FxA', 'sip, esocial, atualizacao', 12, 1),
('SIP', 'eSocial', 'Guia Rápido SIP #016 - eSocial - S-2210 - Comunicação de Acidente de Trabalho (CAT)', 'Como gerar e enviar a CAT (evento S-2210) através do sistema SIP. Link do vídeo: https://www.youtube.com/watch?v=XAAcxzZlLyg', 'sip, cat, esocial, acidente', 13, 1),
('SAUDE', 'Sistemas', 'Semana Cidades Digitais - Dia 2 - Saúde', 'Apresentação completa sobre as soluções Fiorilli para a área da Saúde Municipal. Link do vídeo: https://www.youtube.com/watch?v=jZ5u9FQX_Fw', 'saude, cidades digitais, gestao', 14, 1),
('RH', 'Sistemas', 'Semana Cidades Digitais - Dia 1 - Setor de RH', 'Soluções para Gestão de Pessoas e Recursos Humanos. Link do vídeo: https://www.youtube.com/watch?v=AXnx6wHDUUE', 'rh, folha, pessoal, sip', 15, 1),
('FLOWDOCS', 'Documentos', 'Semana Cidades Digitais - Dia 3 - FlowDocs (Papel Zero)', 'Como implementar a gestão documental digital (Papel Zero) com o FlowDocs. Link do vídeo: https://www.youtube.com/watch?v=pQdKy_K_xvg', 'flowdocs, papel zero, documentos', 16, 1);
